version: '3.8'

services:
  # Keycloak standalone (sem PostgreSQL, mais rápido para desenvolvimento)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak-dev
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_dev_data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  keycloak_dev_data:
    driver: local
