version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Monta o arquivo de configuração do Prometheus no container
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml # Monta o arquivo de regras de alerta no container
    ports:
      - "9090:9090" # Expõe a porta 9090 do Prometheus para acesso externo

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Expõe a porta 3000 do Grafana para acesso externo
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Define a senha do usuário admin do Grafana
    volumes:
      - grafana-storage:/var/lib/grafana # Volume para persistência dos dados e dashboards do Grafana

volumes:
  grafana-storage: # Volume nomeado para armazenar dados do Grafana

# Como funciona:
# - Sobe dois containers: Prometheus (monitoramento/coleta de métricas) e Grafana (visualização de métricas).
# - O Prometheus coleta métricas do endpoint /actuator/prometheus da aplicação Spring Boot.
# - O Grafana se conecta ao Prometheus para criar dashboards e visualizar as métricas coletadas.
# - As portas 9090 (Prometheus) e 3000 (Grafana) ficam disponíveis para acesso via navegador.
