services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import

networks:
  default:
    name: demo-network
    driver: bridge
