spring:
  application:
    name: pedido-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    'org.springframework.web': DEBUG
    'org.springframework.boot.actuate': INFO
